#use standard header
Header header

uint8 lr              #red intensity percentage
uint8 lg              #green intensity percentage
uint8 lb              #blue intensity percentage
float32 lchange_time  #time to reach intensity
uint8 rr              #red intensity percentage
uint8 rg              #green intensity percentage
uint8 rb              #blue intensity percentage
float32 rchange_time  #time to reach intensity

