#use standard header
Header header

#One bool for each parameter.
bool a    # Board communication with the navigation computer
bool b    # Board communication with the sensor&management board
bool c    # Board communication with the left front PI motor controller slave
bool d    # Board communication with the right front PI motor controller slave
bool e    # Board communication with the left rear PI motor controller slave
bool f    # Board communication with the right rear PI motor controller slave