#! /usr/bin/env python
import rospy
import roslib.message
import functools
import sys
import std_msgs.msg
from sam_helpers.thin_writer import SAMWriter

from monarch_msgs.msg import KeyValuePair, KeyValuePairArray

if __name__ == '__main__':
    rospy.init_node('slot_writer', anonymous=True)
    
    writer = SAMWriter('CurrentBehaviorResult', agent_name = 'mbot01')

    message = KeyValuePairArray()
    kvp = KeyValuePair()
    kvp.key = 'test1'
    kvp.value = 'test2'
    message.array.append(kvp)

    rospy.sleep(1)
    writer.publish(message)
    rospy.sleep(1)