#! /usr/bin/env python
import rospy
import roslib.message
import functools
import sys
import std_msgs.msg
from sam_helpers.writer import SAMWriter
from monarch_msgs.msg import KeyValuePair, KeyValuePairArray

if __name__ == '__main__':
    rospy.init_node('slot_writer', anonymous=True)
    
    writer = SAMWriter('CurrentBehaviorResult', agent_name = 'mbot05')

    message = KeyValuePairArray()

    kvp = KeyValuePair()
    kvp.key = 'behavior_name'
    kvp.value = 'gotolocation'

    message.array.append(kvp)

    kvp.key = 'gotolocation'
    kvp.value = 'True'

    message.array.append(kvp)

    rospy.sleep(1)
    writer.publish(message)
    rospy.sleep(1)
