#! /usr/bin/env python
import sys
import yaml
import collections
import exceptions
# ROS
import rospy
import roslib; roslib.load_manifest('monarch_situational_awareness')
import roslib.message
import genpy
# package
from sam_helpers.thin_sam import ThinSAM
from sam_helpers.writer import SAMWriter

if __name__ == '__main__':
    rospy.init_node('thin_sam')

    thin_SAM = ThinSAM()

    thin_SAM.load_yaml_file()

    #for singles in thin_SAM.get_single_slot_args():
    #    SAMWriter(singles.name)

    #for groups in  thin_SAM.get_group_slot_args():
    #    SAMWriter(groups.representative.name, groups.hosts.strip('n'))

    rospy.spin()
