# Define the goal
#uint32 user_id
#PoseStamped target position for escorting

monarch_msgs/KeyValuePairArray goal

---
# Define the result
#bool reached
monarch_msgs/KeyValuePairArray result
---
# Define a feedback message
